libunwind:  # [linux]
  - 1.6  # [linux]
pin_run_as_build:  # [linux]
    libunwind:  # [linux]
      max_pin: x.x  # [linux]
c_compiler_version:
  - 11  # [linux]
  - 14  # [osx]
cxx_compiler_version:
  - 11  # [linux]
  - 14  # [osx]
fortran_compiler_version:
  - 11 
